apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-cm
  namespace: exercise-02
data:
  WORDPRESS_USERNAME: admin
  WORDPRESS_EMAIL: admin@example.com
  WORDPRESS_FIRST_NAME: Rafa
  WORDPRESS_LAST_NAME: Rios
  WORDPRESS_BLOG_NAME: Kubernetes Exercise-02
  MARIADB_HOST: wp-mariadb
  MARIADB_PORT: "3306"
  WORDPRESS_DATABASE_NAME: wp-ex02
  WORDPRESS_TABLE_PREFIX: wp_
  WORDPRESS_DATABASE_USER: wp_user